// 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑
// 🛑 THIS IS AN AUTOGENERATED FILE - DO NOT EDIT DIRECTLY 🛑
// 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑
// @ts-nocheck

import { ENV as _ENV } from 'varlock/env'

export type CoercedEnvSchema = {
	/**
	 * **TRIAL_DAYS**  
	 * ![icon](data:image/svg+xml;utf-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2220%22%20height%3D%2220%22%20viewBox%3D%220%200%2032%2032%22%3E%3Cpath%20fill%3D%22%23808080%22%20d%3D%22M26%2012h-4v2h4v2h-3v2h3v2h-4v2h4a2.003%202.003%200%200%200%202-2v-6a2%202%200%200%200-2-2m-7%2010h-6v-4a2%202%200%200%201%202-2h2v-2h-4v-2h4a2%202%200%200%201%202%202v2a2%202%200%200%201-2%202h-2v2h4ZM8%2020v-8H6v1H4v2h2v5H4v2h6v-2z%22%2F%3E%3C%2Fsvg%3E)  
	 */
	TRIAL_DAYS: number

	/**
	 * **CREDIT_CARD_REQUIRED_FOR_TRIAL**  
	 * ![icon](data:image/svg+xml;utf-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2220%22%20height%3D%2220%22%20viewBox%3D%220%200%2024%2024%22%3E%3Cpath%20fill%3D%22%23808080%22%20d%3D%22M7.885%2010.23L12%203.463l4.116%206.769zm9.606%2011q-1.558%200-2.64-1.081t-1.082-2.64t1.082-2.649t2.64-1.09t2.649%201.09t1.09%202.649t-1.09%202.64t-2.649%201.082m-13.722-.5v-6.462h6.462v6.462z%22%2F%3E%3C%2Fsvg%3E)  
	 */
	CREDIT_CARD_REQUIRED_FOR_TRIAL: 'stripe' | 'manual'
}

type _CoercedEnvSchema_42c7c743 = CoercedEnvSchema

export type EnvSchemaAsStrings = {
	[Property in keyof CoercedEnvSchema]: NonNullable<
		CoercedEnvSchema[Property]
	> extends string
		? NonNullable<CoercedEnvSchema[Property]>
		: NonNullable<CoercedEnvSchema[Property]> extends boolean
			? 'true' | 'false'
			: string
}

type _EnvSchemaAsStrings_42c7c743 = EnvSchemaAsStrings

export type PublicCoercedEnvSchema = Readonly<
	Pick<CoercedEnvSchema, 'TRIAL_DAYS' | 'CREDIT_CARD_REQUIRED_FOR_TRIAL'>
>

// re-export of the runtime ENV proxy, typed to this package's schema
export const ENV = _ENV as unknown as Readonly<CoercedEnvSchema>
